#!/bin/bash

cd $BDB_ROOT/bdb_rep
rm -rf data* rep*.log master* slave*
killall -9 rep_mgr

runRep(){
	# Start the master.
	mkdir master && cd master && mkdir data1
	# rep_mgr -CM -h home -l host:port[-r host:port]
	../gen-input | ../rep_mgr -M -h data1 -l 127.0.0.1:10001 -r 127.0.0.1:10002 -r 127.0.0.1:10003 > rep1.log 2>&1 &
	cd $BDB_ROOT/bdb_rep
	sleep 20

	# Start the first slave.
	mkdir slave1 && cd slave1 && mkdir data2
	../gen-input | ../rep_mgr -C -h data2 -l 127.0.0.1:10002 -r 127.0.0.1:10001 -r 127.0.0.1:10003 > rep2.log 2>&1 &
	cd $BDB_ROOT/bdb_rep
	sleep 20

	# Start the second slave.
	mkdir slave2 && cd slave2 && mkdir data3
	../gen-input | ../rep_mgr -C -h data3 -l 127.0.0.1:10003 -r 127.0.0.1:10001 -r 127.0.0.1:10002 > rep3.log 2>&1 &
	cd $BDB_ROOT/bdb_rep
	sleep 20

	ps -a | grep rep_mgr
	#killall -9 rep_mgr
}

echo "Running rep..."
runRep;



